version: 2

run:
  timeout: 5m
  go: "1.24"

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  revive:
    rules:
      - name: exported
        disabled: true

linters:
  enable:
    - copyloopvar
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
  disable:
    - errcheck # Disabled for now due to controller code issues
    - revive # Disabled for now due to skeleton implementations
    - unused # Disabled for now due to skeleton implementations
  settings:
    gocyclo:
      min-complexity: 20
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
        - gocyclo
        - errcheck
        - gosec
      - path: 'zz_generated\.deepcopy\.go'
        linters:
        - all
