apiVersion: cloud.tencent.com/v1beta1
kind: ClusterBinding
metadata:
  name: example-cluster
spec:
  clusterID: cls-example
  mountNamespace: kubeocean-worker
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubeocean.io/role
        operator: In
        values:
        - worker
  secretRef:
    name: worker-cluster-kubeconfig
    namespace: kubeocean-system