apiVersion: cloud.tencent.com/v1beta1
kind: ClusterBinding
metadata:
  name: example-cluster
  namespace: tapestry-system
spec:
  clusterID: cls-example
  mountNamespace: tapestry-worker
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: role
        operator: In
        values:
        - worker
  secretRef:
    name: worker-cluster-kubeconfig
    namespace: tapestry-system