apiVersion: cloud.tencent.com/v1beta1
kind: ResourceLeasingPolicy
metadata:
  name: example-policy
spec:
  cluster: example-cluster
  forceReclaim: true
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubeocean.io/role
        operator: In
        values: ["worker"]
  timeWindows:
    - start: "18:00"
      end: "08:00"
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
    - start: "00:00"
      end: "23:59"
      days: ["Saturday", "Sunday"]
  resourceLimits:
    - resource: cpu
      quantity: "96"
      percent: 90  # Take the smaller of 4 CPUs or 90% of available CPUs
    - resource: memory
      percent: 95  # Take 95% of available memory
    - resource: nvidia.com/gpu
      percent: 100  # Take 100% of available GPUs