//go:build !ignore_autogenerated

/*
Copyright 2025 Tencent.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedConfig) DeepCopyInto(out *AdvancedConfig) {
	*out = *in
	if in.CLSAgentFileTimeout != nil {
		in, out := &in.CLSAgentFileTimeout, &out.CLSAgentFileTimeout
		*out = new(int32)
		**out = **in
	}
	if in.CLSAgentMaxDepth != nil {
		in, out := &in.CLSAgentMaxDepth, &out.CLSAgentMaxDepth
		*out = new(int32)
		**out = **in
	}
	if in.CLSAgentParseFailMerge != nil {
		in, out := &in.CLSAgentParseFailMerge, &out.CLSAgentParseFailMerge
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedConfig.
func (in *AdvancedConfig) DeepCopy() *AdvancedConfig {
	if in == nil {
		return nil
	}
	out := new(AdvancedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedFilter) DeepCopyInto(out *AdvancedFilter) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = new(int32)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedFilter.
func (in *AdvancedFilter) DeepCopy() *AdvancedFilter {
	if in == nil {
		return nil
	}
	out := new(AdvancedFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CLSDetail) DeepCopyInto(out *CLSDetail) {
	*out = *in
	if in.AdvancedConfig != nil {
		in, out := &in.AdvancedConfig, &out.AdvancedConfig
		*out = new(AdvancedConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AutoIndex != nil {
		in, out := &in.AutoIndex, &out.AutoIndex
		*out = new(string)
		**out = **in
	}
	if in.AutoSplit != nil {
		in, out := &in.AutoSplit, &out.AutoSplit
		*out = new(string)
		**out = **in
	}
	if in.ExcludePaths != nil {
		in, out := &in.ExcludePaths, &out.ExcludePaths
		*out = make([]ExcludePath, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtractRule != nil {
		in, out := &in.ExtractRule, &out.ExtractRule
		*out = new(ExtractRule)
		(*in).DeepCopyInto(*out)
	}
	if in.FullTextIndex != nil {
		in, out := &in.FullTextIndex, &out.FullTextIndex
		*out = new(FullTextIndex)
		**out = **in
	}
	if in.HotPeriod != nil {
		in, out := &in.HotPeriod, &out.HotPeriod
		*out = new(int32)
		**out = **in
	}
	if in.IndexStatus != nil {
		in, out := &in.IndexStatus, &out.IndexStatus
		*out = new(string)
		**out = **in
	}
	if in.Indexs != nil {
		in, out := &in.Indexs, &out.Indexs
		*out = make([]Index, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LogFormat != nil {
		in, out := &in.LogFormat, &out.LogFormat
		*out = new(string)
		**out = **in
	}
	if in.LogType != nil {
		in, out := &in.LogType, &out.LogType
		*out = new(string)
		**out = **in
	}
	if in.LogsetId != nil {
		in, out := &in.LogsetId, &out.LogsetId
		*out = new(string)
		**out = **in
	}
	if in.LogsetName != nil {
		in, out := &in.LogsetName, &out.LogsetName
		*out = new(string)
		**out = **in
	}
	if in.MaxSplitPartitions != nil {
		in, out := &in.MaxSplitPartitions, &out.MaxSplitPartitions
		*out = new(int32)
		**out = **in
	}
	if in.PartitionCount != nil {
		in, out := &in.PartitionCount, &out.PartitionCount
		*out = new(int32)
		**out = **in
	}
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		*out = new(int32)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.StorageType != nil {
		in, out := &in.StorageType, &out.StorageType
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]Tag, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopicId != nil {
		in, out := &in.TopicId, &out.TopicId
		*out = new(string)
		**out = **in
	}
	if in.TopicName != nil {
		in, out := &in.TopicName, &out.TopicName
		*out = new(string)
		**out = **in
	}
	if in.UserDefineRule != nil {
		in, out := &in.UserDefineRule, &out.UserDefineRule
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CLSDetail.
func (in *CLSDetail) DeepCopy() *CLSDetail {
	if in == nil {
		return nil
	}
	out := new(CLSDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerFile) DeepCopyInto(out *ContainerFile) {
	*out = *in
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(string)
		**out = **in
	}
	if in.ContainerOperator != nil {
		in, out := &in.ContainerOperator, &out.ContainerOperator
		*out = new(string)
		**out = **in
	}
	if in.CustomLabels != nil {
		in, out := &in.CustomLabels, &out.CustomLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExcludeLabels != nil {
		in, out := &in.ExcludeLabels, &out.ExcludeLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExcludeNamespace != nil {
		in, out := &in.ExcludeNamespace, &out.ExcludeNamespace
		*out = new(string)
		**out = **in
	}
	if in.FilePaths != nil {
		in, out := &in.FilePaths, &out.FilePaths
		*out = make([]FilePath, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FilePattern != nil {
		in, out := &in.FilePattern, &out.FilePattern
		*out = new(string)
		**out = **in
	}
	if in.IncludeLabels != nil {
		in, out := &in.IncludeLabels, &out.IncludeLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LogPath != nil {
		in, out := &in.LogPath, &out.LogPath
		*out = new(string)
		**out = **in
	}
	if in.MetadataContainer != nil {
		in, out := &in.MetadataContainer, &out.MetadataContainer
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MetadataLabels != nil {
		in, out := &in.MetadataLabels, &out.MetadataLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NsLabelSelector != nil {
		in, out := &in.NsLabelSelector, &out.NsLabelSelector
		*out = new(string)
		**out = **in
	}
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = new(Workload)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerFile.
func (in *ContainerFile) DeepCopy() *ContainerFile {
	if in == nil {
		return nil
	}
	out := new(ContainerFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerStdout) DeepCopyInto(out *ContainerStdout) {
	*out = *in
	if in.AllContainers != nil {
		in, out := &in.AllContainers, &out.AllContainers
		*out = new(bool)
		**out = **in
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(string)
		**out = **in
	}
	if in.ContainerOperator != nil {
		in, out := &in.ContainerOperator, &out.ContainerOperator
		*out = new(string)
		**out = **in
	}
	if in.CustomLabels != nil {
		in, out := &in.CustomLabels, &out.CustomLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExcludeLabels != nil {
		in, out := &in.ExcludeLabels, &out.ExcludeLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ExcludeNamespace != nil {
		in, out := &in.ExcludeNamespace, &out.ExcludeNamespace
		*out = new(string)
		**out = **in
	}
	if in.IncludeLabels != nil {
		in, out := &in.IncludeLabels, &out.IncludeLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MetadataContainer != nil {
		in, out := &in.MetadataContainer, &out.MetadataContainer
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MetadataLabels != nil {
		in, out := &in.MetadataLabels, &out.MetadataLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NsLabelSelector != nil {
		in, out := &in.NsLabelSelector, &out.NsLabelSelector
		*out = new(string)
		**out = **in
	}
	if in.Workloads != nil {
		in, out := &in.Workloads, &out.Workloads
		*out = make([]WorkloadSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerStdout.
func (in *ContainerStdout) DeepCopy() *ContainerStdout {
	if in == nil {
		return nil
	}
	out := new(ContainerStdout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExcludePath) DeepCopyInto(out *ExcludePath) {
	*out = *in
	if in.ExcludeType != nil {
		in, out := &in.ExcludeType, &out.ExcludeType
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExcludePath.
func (in *ExcludePath) DeepCopy() *ExcludePath {
	if in == nil {
		return nil
	}
	out := new(ExcludePath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtractRule) DeepCopyInto(out *ExtractRule) {
	*out = *in
	if in.AdvancedFilters != nil {
		in, out := &in.AdvancedFilters, &out.AdvancedFilters
		*out = make([]AdvancedFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Backtracking != nil {
		in, out := &in.Backtracking, &out.Backtracking
		*out = new(string)
		**out = **in
	}
	if in.BeginningRegex != nil {
		in, out := &in.BeginningRegex, &out.BeginningRegex
		*out = new(string)
		**out = **in
	}
	if in.Delimiter != nil {
		in, out := &in.Delimiter, &out.Delimiter
		*out = new(string)
		**out = **in
	}
	if in.FilterKeys != nil {
		in, out := &in.FilterKeys, &out.FilterKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FilterRegex != nil {
		in, out := &in.FilterRegex, &out.FilterRegex
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IsGBK != nil {
		in, out := &in.IsGBK, &out.IsGBK
		*out = new(string)
		**out = **in
	}
	if in.JsonStandard != nil {
		in, out := &in.JsonStandard, &out.JsonStandard
		*out = new(string)
		**out = **in
	}
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LogRegex != nil {
		in, out := &in.LogRegex, &out.LogRegex
		*out = new(string)
		**out = **in
	}
	if in.RawLogKey != nil {
		in, out := &in.RawLogKey, &out.RawLogKey
		*out = new(string)
		**out = **in
	}
	if in.TimeFormat != nil {
		in, out := &in.TimeFormat, &out.TimeFormat
		*out = new(string)
		**out = **in
	}
	if in.TimeKey != nil {
		in, out := &in.TimeKey, &out.TimeKey
		*out = new(string)
		**out = **in
	}
	if in.UnMatchUpload != nil {
		in, out := &in.UnMatchUpload, &out.UnMatchUpload
		*out = new(string)
		**out = **in
	}
	if in.UnMatchedKey != nil {
		in, out := &in.UnMatchedKey, &out.UnMatchedKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtractRule.
func (in *ExtractRule) DeepCopy() *ExtractRule {
	if in == nil {
		return nil
	}
	out := new(ExtractRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldRef) DeepCopyInto(out *FieldRef) {
	*out = *in
	if in.FieldPath != nil {
		in, out := &in.FieldPath, &out.FieldPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldRef.
func (in *FieldRef) DeepCopy() *FieldRef {
	if in == nil {
		return nil
	}
	out := new(FieldRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilePath) DeepCopyInto(out *FilePath) {
	*out = *in
	if in.File != nil {
		in, out := &in.File, &out.File
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilePath.
func (in *FilePath) DeepCopy() *FilePath {
	if in == nil {
		return nil
	}
	out := new(FilePath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FullTextIndex) DeepCopyInto(out *FullTextIndex) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FullTextIndex.
func (in *FullTextIndex) DeepCopy() *FullTextIndex {
	if in == nil {
		return nil
	}
	out := new(FullTextIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostFile) DeepCopyInto(out *HostFile) {
	*out = *in
	if in.CustomLabels != nil {
		in, out := &in.CustomLabels, &out.CustomLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.FilePaths != nil {
		in, out := &in.FilePaths, &out.FilePaths
		*out = make([]FilePath, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FilePattern != nil {
		in, out := &in.FilePattern, &out.FilePattern
		*out = new(string)
		**out = **in
	}
	if in.LogPath != nil {
		in, out := &in.LogPath, &out.LogPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostFile.
func (in *HostFile) DeepCopy() *HostFile {
	if in == nil {
		return nil
	}
	out := new(HostFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Index) DeepCopyInto(out *Index) {
	*out = *in
	if in.ContainZH != nil {
		in, out := &in.ContainZH, &out.ContainZH
		*out = new(bool)
		**out = **in
	}
	if in.IndexName != nil {
		in, out := &in.IndexName, &out.IndexName
		*out = new(string)
		**out = **in
	}
	if in.IndexType != nil {
		in, out := &in.IndexType, &out.IndexType
		*out = new(string)
		**out = **in
	}
	if in.SqlFlag != nil {
		in, out := &in.SqlFlag, &out.SqlFlag
		*out = new(bool)
		**out = **in
	}
	if in.Tokenizer != nil {
		in, out := &in.Tokenizer, &out.Tokenizer
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Index.
func (in *Index) DeepCopy() *Index {
	if in == nil {
		return nil
	}
	out := new(Index)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InputDetail) DeepCopyInto(out *InputDetail) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.ContainerFile != nil {
		in, out := &in.ContainerFile, &out.ContainerFile
		*out = new(ContainerFile)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerStdout != nil {
		in, out := &in.ContainerStdout, &out.ContainerStdout
		*out = new(ContainerStdout)
		(*in).DeepCopyInto(*out)
	}
	if in.HostFile != nil {
		in, out := &in.HostFile, &out.HostFile
		*out = new(HostFile)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InputDetail.
func (in *InputDetail) DeepCopy() *InputDetail {
	if in == nil {
		return nil
	}
	out := new(InputDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaDetail) DeepCopyInto(out *KafkaDetail) {
	*out = *in
	if in.Brokers != nil {
		in, out := &in.Brokers, &out.Brokers
		*out = new(string)
		**out = **in
	}
	if in.ExtractRule != nil {
		in, out := &in.ExtractRule, &out.ExtractRule
		*out = new(KafkaExtractRule)
		(*in).DeepCopyInto(*out)
	}
	if in.InstanceId != nil {
		in, out := &in.InstanceId, &out.InstanceId
		*out = new(string)
		**out = **in
	}
	if in.KafkaType != nil {
		in, out := &in.KafkaType, &out.KafkaType
		*out = new(string)
		**out = **in
	}
	if in.LogType != nil {
		in, out := &in.LogType, &out.LogType
		*out = new(string)
		**out = **in
	}
	if in.MessageKey != nil {
		in, out := &in.MessageKey, &out.MessageKey
		*out = new(MessageKey)
		(*in).DeepCopyInto(*out)
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(KafkaMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.OutputType != nil {
		in, out := &in.OutputType, &out.OutputType
		*out = new(string)
		**out = **in
	}
	if in.RdKafka != nil {
		in, out := &in.RdKafka, &out.RdKafka
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TimestampFormat != nil {
		in, out := &in.TimestampFormat, &out.TimestampFormat
		*out = new(string)
		**out = **in
	}
	if in.TimestampKey != nil {
		in, out := &in.TimestampKey, &out.TimestampKey
		*out = new(string)
		**out = **in
	}
	if in.Topic != nil {
		in, out := &in.Topic, &out.Topic
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaDetail.
func (in *KafkaDetail) DeepCopy() *KafkaDetail {
	if in == nil {
		return nil
	}
	out := new(KafkaDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaExtractRule) DeepCopyInto(out *KafkaExtractRule) {
	*out = *in
	if in.BeginningRegex != nil {
		in, out := &in.BeginningRegex, &out.BeginningRegex
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaExtractRule.
func (in *KafkaExtractRule) DeepCopy() *KafkaExtractRule {
	if in == nil {
		return nil
	}
	out := new(KafkaExtractRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaMetadata) DeepCopyInto(out *KafkaMetadata) {
	*out = *in
	if in.FormatType != nil {
		in, out := &in.FormatType, &out.FormatType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaMetadata.
func (in *KafkaMetadata) DeepCopy() *KafkaMetadata {
	if in == nil {
		return nil
	}
	out := new(KafkaMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogConfig) DeepCopyInto(out *LogConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogConfig.
func (in *LogConfig) DeepCopy() *LogConfig {
	if in == nil {
		return nil
	}
	out := new(LogConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogConfigList) DeepCopyInto(out *LogConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LogConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogConfigList.
func (in *LogConfigList) DeepCopy() *LogConfigList {
	if in == nil {
		return nil
	}
	out := new(LogConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogConfigSpec) DeepCopyInto(out *LogConfigSpec) {
	*out = *in
	if in.CLSDetail != nil {
		in, out := &in.CLSDetail, &out.CLSDetail
		*out = new(CLSDetail)
		(*in).DeepCopyInto(*out)
	}
	if in.InputDetail != nil {
		in, out := &in.InputDetail, &out.InputDetail
		*out = new(InputDetail)
		(*in).DeepCopyInto(*out)
	}
	if in.KafkaDetail != nil {
		in, out := &in.KafkaDetail, &out.KafkaDetail
		*out = new(KafkaDetail)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogConfigSpec.
func (in *LogConfigSpec) DeepCopy() *LogConfigSpec {
	if in == nil {
		return nil
	}
	out := new(LogConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogConfigStatus) DeepCopyInto(out *LogConfigStatus) {
	*out = *in
	if in.Code != nil {
		in, out := &in.Code, &out.Code
		*out = new(string)
		**out = **in
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogConfigStatus.
func (in *LogConfigStatus) DeepCopy() *LogConfigStatus {
	if in == nil {
		return nil
	}
	out := new(LogConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MessageKey) DeepCopyInto(out *MessageKey) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(ValueFrom)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MessageKey.
func (in *MessageKey) DeepCopy() *MessageKey {
	if in == nil {
		return nil
	}
	out := new(MessageKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueFrom) DeepCopyInto(out *ValueFrom) {
	*out = *in
	if in.FieldRef != nil {
		in, out := &in.FieldRef, &out.FieldRef
		*out = new(FieldRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueFrom.
func (in *ValueFrom) DeepCopy() *ValueFrom {
	if in == nil {
		return nil
	}
	out := new(ValueFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Workload) DeepCopyInto(out *Workload) {
	*out = *in
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Workload.
func (in *Workload) DeepCopy() *Workload {
	if in == nil {
		return nil
	}
	out := new(Workload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSelector) DeepCopyInto(out *WorkloadSelector) {
	*out = *in
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(string)
		**out = **in
	}
	if in.ContainerOperator != nil {
		in, out := &in.ContainerOperator, &out.ContainerOperator
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSelector.
func (in *WorkloadSelector) DeepCopy() *WorkloadSelector {
	if in == nil {
		return nil
	}
	out := new(WorkloadSelector)
	in.DeepCopyInto(out)
	return out
}
